spring:
  application:
    name: ai-banking-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
#          max-completion-tokens: 1000

server:
  port: 8082

logging:
  level:
    root: INFO
    com.rajeswarandhandapani: DEBUG
    org.springframework.ai: DEBUG