spring:
  application:
    name: ai-banking-service
  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-mini
#          max-completion-tokens: 1000


logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG