spring:
  application:
    name: ai-banking-service
  ai:
    openai:
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
#          max-completion-tokens: 1000


logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG