spring:
  application:
    name: ai-banking-service
  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.7
#          max-completion-tokens: 1000

server:
  port: 8082

logging:
  level:
    root: INFO
    com.rajeswarandhandapani: DEBUG
    org.springframework.ai: DEBUG